version: "3.9"
services:
  nextjs:
    image: wf-tracker
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always
